source "https://rubygems.org"

ruby "3.2.2"
gem "active_storage_validations", "0.9.8"
gem "bootsnap", require: false
gem "config"
gem "devise"
gem "faker", "2.21.0"
gem "figaro"
gem "image_processing", "~> 1.2"
gem "jsonapi-serializer"
gem "mysql2", "~> 0.5"
gem "pagy"
gem "pry-rails"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "ransack"
gem "tzinfo-data", platforms: %i(windows jruby)

group :development, :test do
  gem "debug", platforms: %i(mri mingw x64_mingw)
  gem "factory_bot_rails"
  gem "rails-controller-testing"
  gem "rspec-rails", "~> 4.0.1"
  gem "rubocop", "~> 1.26", require: false
  gem "rubocop-checkstyle_formatter", require: false
  gem "rubocop-rails", "~> 2.14.0", require: false
  gem "shoulda-matchers", "~> 5.0"
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end
